# Generated by Django 6.0.5 on 2026-05-11 02:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='项目名称')),
                ('description', models.TextField(verbose_name='项目描述')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='结束日期')),
                ('status', models.CharField(choices=[('planning', '规划中'), ('ongoing', '进行中'), ('completed', '已完成'), ('suspended', '已暂停')], default='planning', max_length=20, verbose_name='项目状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('principal_investigator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='led_projects', to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
            ],
            options={
                'verbose_name': '科研项目',
                'verbose_name_plural': '科研项目',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResearchData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='数据标题')),
                ('description', models.TextField(blank=True, null=True, verbose_name='数据描述')),
                ('file', models.FileField(upload_to='research_data/', verbose_name='数据文件')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('file_size', models.BigIntegerField(verbose_name='文件大小(字节)')),
                ('file_type', models.CharField(max_length=50, verbose_name='文件类型')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_data', to=settings.AUTH_USER_MODEL, verbose_name='上传者')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_files', to='core.researchproject', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '科研数据',
                'verbose_name_plural': '科研数据',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
