# Generated by Django 6.0.5 on 2026-05-11 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researchproject',
            name='principal_investigator',
        ),
        migrations.CreateModel(
            name='PlatformApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_cn', models.CharField(max_length=200, verbose_name='平台中文名称')),
                ('name_en', models.CharField(max_length=200, verbose_name='平台英文名称')),
                ('category', models.CharField(max_length=50, verbose_name='平台类别')),
                ('level', models.CharField(max_length=50, verbose_name='平台级别')),
                ('department', models.CharField(max_length=200, verbose_name='主管部门')),
                ('depend_unit', models.CharField(max_length=200, verbose_name='依托单位')),
                ('approve_time', models.DateField(verbose_name='批准设立时间')),
                ('approve_no', models.CharField(max_length=100, verbose_name='批准文号')),
                ('position', models.TextField(verbose_name='平台定位')),
                ('target', models.TextField(verbose_name='总体目标')),
                ('direction', models.TextField(verbose_name='主要研究方向')),
                ('leader', models.CharField(max_length=100, verbose_name='平台负责人')),
                ('admin_leader', models.CharField(blank=True, max_length=100, null=True, verbose_name='行政负责人')),
                ('tech_leader', models.CharField(blank=True, max_length=100, null=True, verbose_name='技术负责人')),
                ('contact_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='平台联系人')),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='联系电话')),
                ('inner_rule', models.TextField(verbose_name='内部管理制度')),
                ('fixed_person_total', models.IntegerField(verbose_name='固定人员总数')),
                ('core_person_num', models.IntegerField(verbose_name='核心骨干人数')),
                ('title_structure', models.TextField(verbose_name='人员职称结构')),
                ('education_structure', models.TextField(verbose_name='人员学历结构')),
                ('academic_leader', models.TextField(verbose_name='学术带头人信息')),
                ('room_area', models.CharField(max_length=100, verbose_name='科研用房面积')),
                ('lab_num', models.IntegerField(verbose_name='实验室数量')),
                ('equipment_total', models.IntegerField(verbose_name='仪器设备总台套数')),
                ('equipment_value', models.CharField(max_length=100, verbose_name='仪器设备总原值')),
                ('national_project_num', models.IntegerField(verbose_name='年度国家级项目数')),
                ('provincial_project_num', models.IntegerField(verbose_name='年度省部级项目数')),
                ('open_rule', models.TextField(verbose_name='对外开放机制')),
                ('service_target', models.CharField(max_length=200, verbose_name='主要服务对象')),
                ('service_company_num', models.IntegerField(verbose_name='年度服务企业数')),
                ('year_fund_total', models.CharField(max_length=100, verbose_name='年度经费总额')),
                ('asset_manage', models.TextField(verbose_name='资产管理情况')),
                ('safe_rule', models.TextField(verbose_name='安全管理制度')),
                ('long_term_plan', models.TextField(verbose_name='中长期发展规划')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已驳回')], default='pending', max_length=20, verbose_name='申请状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
            ],
            options={
                'verbose_name': '平台入驻申请',
                'verbose_name_plural': '平台入驻申请',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='ResearchData',
        ),
        migrations.DeleteModel(
            name='ResearchProject',
        ),
    ]
