# Generated by Django 6.0.5 on 2026-06-01 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformapplication',
            name='academic_committee_duty',
            field=models.TextField(blank=True, default='', null=True, verbose_name='学术/技术委员会职责'),
        ),
        migrations.AddField(
            model_name='platformapplication',
            name='academic_committee_structure',
            field=models.TextField(blank=True, default='', null=True, verbose_name='学术/技术委员会组成'),
        ),
        migrations.AddField(
            model_name='platformapplication',
            name='accept_status',
            field=models.CharField(default='0', max_length=10, verbose_name='验收状态'),
        ),
        migrations.AddField(
            model_name='platformapplication',
            name='achievement_transformation_num',
            field=models.IntegerField(default=0, verbose_name='成果转化项目数'),
        ),
        migrations.AddField(
            model_name='platformapplication',
            name='age_structure',
            field=models.TextField(blank=True, default='', null=True, verbose_name='人员年龄结构'),
        ),
        migrations.AddField(
            model_name='platformapplication',
            name='annual_service_income',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='年度服务收入总额'),
        ),
        migrations.AddField(
            model_name='platformapplication',
            name='annual_work_plan',
            field=models.TextField(blank=True, default='', null=True, verbose_name='年度工作计划'),
        ),
        migrations.AddField(
            model_name='platformapplication',
            name='annual_work_summary',
            field=models.TextField(blank=True, default='', null=True, verbose_name='年度工作总结'),
        ),
        migrations.AddField(
            model_name='platformapplication',
            name='award_level_and_name',
            field=models.TextField(blank=True, default='', null=True, verbose_name='奖励级别及名称'),
        ),
        migrations.AddField(
            model_name='platformapplication',
            name='charging_standard',
            field=models.TextField(blank=True, default='', null=True, verbose_name='收费标准'),
        ),
        migrations.AddField(
            model_name='platformapplication',
            name='cooperate_unit',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='合作单位'),
        ),
        migrations.AddField(
            model_name='platformapplication',
            name='flowing_personnel',
            field=models.TextField(blank=True, default='', null=True, verbose_name='流动人员情况'),
        ),
        migrations.AddField(
            model_name='platformapplication',
            name='funding_source_structure',
            field=models.TextField(blank=True, default='', null=True, verbose_name='经费来源结构'),
        ),
        migrations.AddField(
            model_name='platformapplication',
            name='high_level_talent',
            field=models.TextField(blank=True, default='', null=True, verbose_name='高层次人才情况'),
        ),
        migrations.AddField(
            model_name='platformapplication',
            name='improvement_measures',
            field=models.TextField(blank=True, default='', null=True, verbose_name='改进措施'),
        ),
        migrations.AddField(
            model_name='platformapplication',
            name='industry_university_research_project_num',
            field=models.IntegerField(default=0, verbose_name='产学研合作项目数'),
        ),
        migrations.AddField(
            model_name='platformapplication',
            name='invention_patent_num',
            field=models.IntegerField(default=0, verbose_name='年度授权发明专利数'),
        ),
        migrations.AddField(
            model_name='platformapplication',
            name='main_large_equipment',
            field=models.TextField(blank=True, default='', null=True, verbose_name='主要大型仪器设备'),
        ),
        migrations.AddField(
            model_name='platformapplication',
            name='main_problems',
            field=models.TextField(blank=True, default='', null=True, verbose_name='存在主要问题'),
        ),
        migrations.AddField(
            model_name='platformapplication',
            name='monograph_num',
            field=models.IntegerField(default=0, verbose_name='年度出版专著数'),
        ),
        migrations.AddField(
            model_name='platformapplication',
            name='organization_structure',
            field=models.TextField(blank=True, default='', null=True, verbose_name='管理机构设置'),
        ),
        migrations.AddField(
            model_name='platformapplication',
            name='performance_evaluation_result',
            field=models.TextField(blank=True, default='', null=True, verbose_name='运行绩效考核结果'),
        ),
        migrations.AddField(
            model_name='platformapplication',
            name='pilot_base_situation',
            field=models.TextField(blank=True, default='', null=True, verbose_name='中试基地情况'),
        ),
        migrations.AddField(
            model_name='platformapplication',
            name='popular_science_training_activity_num',
            field=models.IntegerField(default=0, verbose_name='科普与培训活动次数'),
        ),
        migrations.AddField(
            model_name='platformapplication',
            name='reservation_method',
            field=models.TextField(blank=True, default='', null=True, verbose_name='预约方式'),
        ),
        migrations.AddField(
            model_name='platformapplication',
            name='resource_database_situation',
            field=models.TextField(blank=True, default='', null=True, verbose_name='资源库/数据库情况'),
        ),
        migrations.AddField(
            model_name='platformapplication',
            name='sci_ei_paper_num',
            field=models.IntegerField(default=0, verbose_name='年度发表SCI/EI论文数'),
        ),
        migrations.AddField(
            model_name='platformapplication',
            name='science_award_num',
            field=models.IntegerField(default=0, verbose_name='年度获得科技奖励数'),
        ),
        migrations.AddField(
            model_name='platformapplication',
            name='shared_service_process',
            field=models.TextField(blank=True, default='', null=True, verbose_name='共享服务流程'),
        ),
        migrations.AddField(
            model_name='platformapplication',
            name='talent_training',
            field=models.TextField(blank=True, default='', null=True, verbose_name='人才培养机制'),
        ),
        migrations.AddField(
            model_name='platformapplication',
            name='technical_service_income',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='技术服务收入'),
        ),
        migrations.AddField(
            model_name='platformapplication',
            name='together_unit',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='共建单位'),
        ),
        migrations.AddField(
            model_name='platformapplication',
            name='utility_model_patent_num',
            field=models.IntegerField(default=0, verbose_name='年度授权实用新型专利数'),
        ),
        migrations.AddField(
            model_name='platformapplication',
            name='valid_period',
            field=models.CharField(default='', max_length=100, verbose_name='建设期'),
        ),
        migrations.AlterField(
            model_name='platformapplication',
            name='academic_leader',
            field=models.TextField(default='', verbose_name='学术带头人信息'),
        ),
        migrations.AlterField(
            model_name='platformapplication',
            name='admin_leader',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='行政负责人'),
        ),
        migrations.AlterField(
            model_name='platformapplication',
            name='approve_no',
            field=models.CharField(default='', max_length=100, verbose_name='批准文号'),
        ),
        migrations.AlterField(
            model_name='platformapplication',
            name='approve_time',
            field=models.DateField(null=True, verbose_name='批准设立时间'),
        ),
        migrations.AlterField(
            model_name='platformapplication',
            name='asset_manage',
            field=models.TextField(default='', verbose_name='资产管理情况'),
        ),
        migrations.AlterField(
            model_name='platformapplication',
            name='category',
            field=models.CharField(default='', max_length=50, verbose_name='平台类别'),
        ),
        migrations.AlterField(
            model_name='platformapplication',
            name='contact_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='平台联系人'),
        ),
        migrations.AlterField(
            model_name='platformapplication',
            name='contact_phone',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='联系电话'),
        ),
        migrations.AlterField(
            model_name='platformapplication',
            name='core_person_num',
            field=models.IntegerField(default=0, verbose_name='核心骨干人数'),
        ),
        migrations.AlterField(
            model_name='platformapplication',
            name='department',
            field=models.CharField(default='', max_length=200, verbose_name='主管部门'),
        ),
        migrations.AlterField(
            model_name='platformapplication',
            name='depend_unit',
            field=models.CharField(default='', max_length=200, verbose_name='依托单位'),
        ),
        migrations.AlterField(
            model_name='platformapplication',
            name='direction',
            field=models.TextField(default='', verbose_name='主要研究方向'),
        ),
        migrations.AlterField(
            model_name='platformapplication',
            name='education_structure',
            field=models.TextField(default='', verbose_name='人员学历结构'),
        ),
        migrations.AlterField(
            model_name='platformapplication',
            name='equipment_total',
            field=models.IntegerField(default=0, verbose_name='仪器设备总台套数'),
        ),
        migrations.AlterField(
            model_name='platformapplication',
            name='equipment_value',
            field=models.CharField(default='', max_length=100, verbose_name='仪器设备总原值'),
        ),
        migrations.AlterField(
            model_name='platformapplication',
            name='fixed_person_total',
            field=models.IntegerField(default=0, verbose_name='固定人员总数'),
        ),
        migrations.AlterField(
            model_name='platformapplication',
            name='inner_rule',
            field=models.TextField(default='', verbose_name='内部管理制度'),
        ),
        migrations.AlterField(
            model_name='platformapplication',
            name='lab_num',
            field=models.IntegerField(default=0, verbose_name='实验室数量'),
        ),
        migrations.AlterField(
            model_name='platformapplication',
            name='leader',
            field=models.CharField(default='', max_length=100, verbose_name='平台负责人'),
        ),
        migrations.AlterField(
            model_name='platformapplication',
            name='level',
            field=models.CharField(default='', max_length=50, verbose_name='平台级别'),
        ),
        migrations.AlterField(
            model_name='platformapplication',
            name='long_term_plan',
            field=models.TextField(default='', verbose_name='中长期发展规划'),
        ),
        migrations.AlterField(
            model_name='platformapplication',
            name='name_cn',
            field=models.CharField(default='', max_length=200, verbose_name='平台中文名称'),
        ),
        migrations.AlterField(
            model_name='platformapplication',
            name='name_en',
            field=models.CharField(default='', max_length=200, verbose_name='平台英文名称'),
        ),
        migrations.AlterField(
            model_name='platformapplication',
            name='national_project_num',
            field=models.IntegerField(default=0, verbose_name='年度国家级项目数'),
        ),
        migrations.AlterField(
            model_name='platformapplication',
            name='open_rule',
            field=models.TextField(default='', verbose_name='对外开放机制'),
        ),
        migrations.AlterField(
            model_name='platformapplication',
            name='position',
            field=models.TextField(default='', verbose_name='平台定位'),
        ),
        migrations.AlterField(
            model_name='platformapplication',
            name='provincial_project_num',
            field=models.IntegerField(default=0, verbose_name='年度省部级项目数'),
        ),
        migrations.AlterField(
            model_name='platformapplication',
            name='room_area',
            field=models.CharField(default='', max_length=100, verbose_name='科研用房面积'),
        ),
        migrations.AlterField(
            model_name='platformapplication',
            name='safe_rule',
            field=models.TextField(default='', verbose_name='安全管理制度'),
        ),
        migrations.AlterField(
            model_name='platformapplication',
            name='service_company_num',
            field=models.IntegerField(default=0, verbose_name='年度服务企业数'),
        ),
        migrations.AlterField(
            model_name='platformapplication',
            name='service_target',
            field=models.CharField(default='', max_length=200, verbose_name='主要服务对象'),
        ),
        migrations.AlterField(
            model_name='platformapplication',
            name='target',
            field=models.TextField(default='', verbose_name='总体目标'),
        ),
        migrations.AlterField(
            model_name='platformapplication',
            name='tech_leader',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='技术负责人'),
        ),
        migrations.AlterField(
            model_name='platformapplication',
            name='title_structure',
            field=models.TextField(default='', verbose_name='人员职称结构'),
        ),
        migrations.AlterField(
            model_name='platformapplication',
            name='year_fund_total',
            field=models.CharField(default='', max_length=100, verbose_name='年度经费总额'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='company',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='单位名称'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nickname',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='昵称'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=11, null=True, verbose_name='联系电话'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='real_name',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='真实姓名'),
        ),
    ]
